### ISSUE TITLE
Crashes on 1.16.5 Server

### ISSUE THREAD

**Issue by Uplink1209** [user11681/limitless#35]
Running on latest version of fabric mod loader and api for 1.16.5, on limitless 1.1.2.
Server does not launch on both java 8 and 11
No other mods used, latest version that launched was 1.0.2, anything after doesn't launch.
(I need 1.1.0 or later to use carpet on the server)

```[10:33:33] [main/INFO]: no good? no, this man is definitely up to evil.
Exception in thread "main" java.lang.RuntimeException: Failed to setup Fabric server environment!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:52)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred when launching the server!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:108)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50)
Caused by: java.lang.RuntimeException: An exception occurred when launching the
server!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:64)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106)
        ... 1 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62)
        ... 2 more
Caused by: java.lang.ExceptionInInitializerError
        at net.devtech.grossfabrichacks.unsafe.UnsafeUtil.<clinit>(UnsafeUtil.java:182)
        at net.devtech.grossfabrichacks.GrossFabricHacks.<clinit>(GrossFabricHacks.java:137)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Unknown Source)
        at net.fabricmc.loader.FabricLoader.setupLanguageAdapters(FabricLoader.java:402)
        at net.fabricmc.loader.FabricLoader.finishModLoading(FabricLoader.java:262)
        at net.fabricmc.loader.FabricLoader.freeze(FabricLoader.java:107)
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127)
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:27)
        ... 7 more
Caused by: java.lang.ClassNotFoundException: jdk.internal.access.JavaLangAccess
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:56)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Unknown Source)
        at user11681.reflect.Classes.load(Classes.java:246)
        at user11681.reflect.Classes.<clinit>(Classes.java:392)
        ... 16 more```

**Comment by user11681** [comment]
From which vendor is your JVM?

**Comment by Uplink1209** [comment]
Running AdoptOpenJDK 8 Openj9 and AdoptOpenJDK 11 Hotspot

**Comment by user11681** [comment]
I have released a [new version](https://github.com/user11681/limitless/releases/tag/1.1.3) that works for me with these JREs.

**Comment by Uplink1209** [comment]
Works wonderfully now, thanks!
